(*********************************************************************************)
(*  mdexp - Literate Programming with Embedded Snapshots                         *)
(*  SPDX-FileCopyrightText: 2025-2026 Mathieu Barbin <mathieu.barbin@gmail.com>  *)
(*  SPDX-License-Identifier: LGPL-3.0-or-later WITH LGPL-3.0-linking-exception   *)
(*********************************************************************************)

(* @mdexp *)
(* # Code Block with Blank Comment Lines Test (OCaml) *)
(*  *)
(* This test verifies that blank comment lines within code blocks don't *)
(* prematurely end the block in OCaml files. *)
(* @mdexp.end *)

(* @mdexp *)
(* ## Function with blank lines in comments *)
(*  *)
(* The following code has blank comment lines that should be preserved: *)
(* @mdexp.end *)

(* @mdexp.code *)
(* let calculate x y = *)
(*   let sum = x + y in *)
(*   *)
(*   let result = sum * 2 in *)
(*   result *)
(* @mdexp.end *)

(* @mdexp *)
(* ## Multiple functions with blank lines *)
(* @mdexp.end *)

(* @mdexp.code *)
(* let first () = *)
(*   let a = 1 in *)
(*   *)
(*   let b = 2 in *)
(*   a + b *)
(*  *)
(* let second () = *)
(*   let c = 3 in *)
(*   c *)
(* @mdexp.end *)
