name: deploy-doc

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest

    env:
      MDBOOK_VERSION: "0.5.2"
      MDBOOK_DIGEST: "sha256:b7ab218618bb3c1715e3e1759cfa0abc56dcd7ab5d90f60dcd86d708c87b715d"
      ZOLA_VERSION: "0.22.1"
      ZOLA_DIGEST: "sha256:45de6b2559aba4df42199dc6b0161acb914d37be4ccaa03297cd4a26c8e14042"

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Cache mdbook binary
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        id: mdbook-cache
        with:
          path: ~/.local/bin/mdbook
          key: mdbook-${{ env.MDBOOK_VERSION }}-${{ runner.os }}-${{ runner.arch }}-${{ env.MDBOOK_DIGEST }}

      - name: Install mdbook
        env:
          BINARY_CACHE_HIT: ${{ steps.mdbook-cache.outputs.cache-hit }}
        run: |
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          bash actions/install-mdbook.sh

      - name: Cache zola binary
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        id: zola-cache
        with:
          path: ~/.local/bin/zola
          key: zola-${{ env.ZOLA_VERSION }}-${{ runner.os }}-${{ runner.arch }}-${{ env.ZOLA_DIGEST }}

      - name: Install zola
        env:
          BINARY_CACHE_HIT: ${{ steps.zola-cache.outputs.cache-hit }}
        run: |
          bash actions/install-zola.sh

      - name: Build documentation
        run: make -C doc build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: doc/public

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
